name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositori
      uses: actions/checkout@v3

    - name: Configurar JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # Si el projecte usa Maven, executa Maven per compilar i fer tests
    - name: Compilar i executar testos amb Maven
      run: mvn clean test || echo "Maven no detectat, es compilarà manualment"

    #- name: Executar testos amb JUnit manualment
    #  run: |
    #    java -cp target/test-classes:target/classes:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar \
    #      org.junit.runner.JUnitCore org.JavaCar.VehicleTest org.JavaCar.LlogableGestorTest

    # Publicar resultats dels tests en el workflow summary
    #- name: Publicar resultats dels tests
    #  run: echo "Consulta els logs per veure els errors si els tests fallen" >> $GITHUB_STEP_SUMMARY

    - name: Executar testos amb JUnit
      id: run_tests
      run: |
        mvn test | tee test-results.log
      continue-on-error: true

    - name: Publicar resultats dels testos a GitHub Actions
      run: |
        echo "### 📝 Resultats dels testos" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        grep -E "Tests run:|Failures:|Errors:|Skipped:" test-results.log >> $GITHUB_STEP_SUMMARY

    - name: Marcar el workflow com a fallit si hi ha errors
      run: |
        if grep -q "Failures: [1-9]" test-results.log || grep -q "Errors: [1-9]" test-results.log; then
          echo "❌ S'han detectat errors en els testos. Consulta els logs."
          exit 1
        fi